DEFAULT_ICORTEX_CONFIG_PATH = "icortex.toml"
DEFAULT_CACHE_PATH = "cache.json"
DEFAULT_REGENERATE = False
DEFAULT_AUTO_INSTALL_PACKAGES = False
DEFAULT_HIDE_CODE = False
DEFAULT_SERVICE = "textcortex"